### ISSUE TITLE
incrément/décrément du stock

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/woo-oyst#76]
Quand une commande est passée via freepay:
- ETQ plugin, je décrémente le stock
- ETQ plugin, si fraud validation = KO alors je remets le stock

1er point : ok
2eme point : du dev a faire car ce n'est pas natif sur woocommerce

**Comment by fredichisar** [comment]
<img width="321" alt="capture d ecran 2017-09-20 a 17 16 51" src="https://user-images.githubusercontent.com/29376303/30652030-95f32b9c-9e27-11e7-8027-a49a81bc795f.png">
