### ISSUE TITLE
logo Oyst à intégrer

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/woo-oyst#79]
Il faut supprimer le logo freepay et mettre celui ci: 
![logo_oyst_blanc_800](https://user-images.githubusercontent.com/27730079/30650906-6848c61e-9e24-11e7-9c0b-72d67a9aedf0.png)

Il faut le mettre dans les deux confs

**Comment by fredichisar** [comment]
Ok peux tu le fournir à la bonne taille stp

**Comment by fredichisar** [comment]
<img width="731" alt="capture d ecran 2017-09-20 a 17 25 51" src="https://user-images.githubusercontent.com/29376303/30652492-cebeb8be-9e28-11e7-84fd-6adb67c6db08.png">

**Comment by fredichisar** [comment]
<img width="682" alt="capture d ecran 2017-09-20 a 17 29 43" src="https://user-images.githubusercontent.com/29376303/30652686-4f95b33e-9e29-11e7-8daa-7e69da98361f.png">
