### ISSUE TITLE
changer pictogramme pour commandes freepay

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/woo-oyst#81]
Refacto des pastilles:

To do:
Commande en pending: jaune
Commande en fraud validation ok -> processing : vert
Commande en fraud validation ko : rouge
Commande cancel ok: vert
Commande capturée : vert
Commande refund ok : vert

**Comment by fredichisar** [comment]
green: #73a724
red: #a00
orange: #ffba00
yellow: #d0c21f

**Comment by fredichisar** [comment]
Done
