### ISSUE TITLE
Bouton 1-click à la page recap du panier (plusieurs produits)

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/woo-oyst#89]
Changer la version dans l'authorize (V2)

**Comment by rbenezra** [comment]
https://one-click-api.readme.io/reference#bouton-sur-la-page-panier

![image](https://user-images.githubusercontent.com/32451092/31612633-a32d34c0-b280-11e7-80aa-a968facbf621.png)

**Emplacement du bouton 1C**
![page panier](https://user-images.githubusercontent.com/32451092/31614310-3e831ab6-b286-11e7-9359-06e846944479.png)
