### ISSUE TITLE
Emplacement du bouton 1-Click

### ISSUE THREAD

**Issue by rbenezra** [oystparis/woo-oyst#91]
ETQM : plusieurs options pour la personnalisation du bouton one-click pas toutes fonctionnelles et doublons. En particulier, deux fois ''Avant le formulaire ''Ajouter au panier'' '' et l'un des deux pas fonctionnel.

**Comment by fredichisar** [comment]
Le choix proposé dans le menu déroulant se base sur la structure de WooCommerce, par contre, tous les thèmes ne propose pas tous ces hooks... Il est possible de réduire ce choix si besoin

**Comment by rbenezra** [comment]
![image](https://user-images.githubusercontent.com/32451092/32595818-a528d8c4-c531-11e7-9e50-41b0999f98ca.png)
doublons
